### ISSUE TITLE
:ticket:Worker class Groundwork - Link subclass

### ISSUE THREAD

**Issue by VuceticBranislav** [HECalculator/HECalculator-Desk#7]
Linked  to: #5 
Link subclasses to Worker class

- [x] Link Inputs class
- [x] Link States class
- [ ] Link Report class
- [ ] Link Results class
